export const EBAY_MAIN_CATEGORIES = [
  { categoryId: "1", categoryName: "Collectibles" },
  { categoryId: "99", categoryName: "Everything Else" },
  { categoryId: "220", categoryName: "Toys & Hobbies" },
  //   { categoryId: "237", categoryName: "Dolls & Bears" },
  //   { categoryId: "260", categoryName: "Stamps" },
  { categoryId: "267", categoryName: "Books & Magazines" },
  { categoryId: "281", categoryName: "Jewelry & Watches" },
  { categoryId: "293", categoryName: "Consumer Electronics" },
  //   { categoryId: "316", categoryName: "Specialty Services" },
  { categoryId: "550", categoryName: "Art" },
  { categoryId: "619", categoryName: "Musical Instruments & Gear" },
  { categoryId: "625", categoryName: "Cameras & Photo" },
  { categoryId: "870", categoryName: "Pottery & Glass" },
  { categoryId: "888", categoryName: "Sporting Goods" },
  { categoryId: "1249", categoryName: "Video Games & Consoles" },
  { categoryId: "1281", categoryName: "Pet Supplies" },
  { categoryId: "1305", categoryName: "Tickets & Experiences" },
  //   { categoryId: "2984", categoryName: "Baby" },
  { categoryId: "3252", categoryName: "Travel" },
  //   { categoryId: "10542", categoryName: "Real Estate" },
  //   { categoryId: "11116", categoryName: "Coins & Paper Money" },
  { categoryId: "11232", categoryName: "Movies & TV" },
  { categoryId: "11233", categoryName: "Music" },
  { categoryId: "11450", categoryName: "Clothing, Shoes & Accessories" },
  { categoryId: "11700", categoryName: "Home & Garden" },
  //   { categoryId: "12576", categoryName: "Business & Industrial" },
  { categoryId: "14339", categoryName: "Crafts" },
  { categoryId: "15032", categoryName: "Cell Phones & Accessories" },
  { categoryId: "20081", categoryName: "Antiques" },
  { categoryId: "26395", categoryName: "Health & Beauty" },
  //   { categoryId: "45100", categoryName: "Entertainment Memorabilia" },
  { categoryId: "58058", categoryName: "Computers/Tablets & Networking" },
  { categoryId: "64482", categoryName: "Sports Mem, Cards & Fan Shop" },
  //   { categoryId: "172008", categoryName: "Gift Cards & Coupons" },
];
