export const CATEGORIES = [
	"No Selection",
	"Clothing, Shoes & Accessories",
	"Health & Beauty",
	"Toys & Hobbies",
	"Books & Magazines",
	"Jewelry & Watches",
	"Consumer Electronics",
	"Musical Instruments & Gear",
	"Cameras & Photo",
	"Pottery & Glass",
	"Sporting Goods",
	"Video Games & Consoles",
	"Travel",
	"Home & Garden",
	"Everything Else...",
];
