export const CATEGORIES = [
	{ value: "none", label: "No Selection" },
	{ value: "11450", label: "Clothing, Shoes & Accessories" },
	{ value: "26395", label: "Health & Beauty" },
	{ value: "220", label: "Toys & Hobbies" },
	{ value: "267", label: "Books & Magazines" },
	{ value: "281", label: "Jewelry & Watches" },
	{ value: "293", label: "Consumer Electronics" },
	{ value: "619", label: "Musical Instruments & Gear" },
	{ value: "625", label: "Cameras & Photo" },
	{ value: "870", label: "Pottery & Glass" },
	{ value: "888", label: "Sporting Goods" },
	{ value: "1249", label: "Video Games & Consoles" },
	{ value: "3252", label: "Travel" },
	{ value: "11700", label: "Home & Garden" },
	{ value: "99", label: "Everything Else..." },
];
